#!/bin/sh
sudo -v

# Clost all system preferences panes to prevent them from overriding
osascript -e 'tell application "System Preferences" to quit'

# Keep alive sudo permission
while true; do sudo -n true; sleep 60; kill -0 "$$" || exit; done 2>/dev/null &

# Set sidebar icon side to medium
defaults write NSGlobalDomain NSTableViewDefaultSizeMode -int 2

# System: disable dmg verification
defaults write com.apple.frameworks.diskimages skip-verify -bool true
defaults write com.apple.frameworks.diskimages skip-verify-locked -bool true
defaults write com.apple.frameworks.diskimages skip-verify-remote -bool true

# System: allow open application from anywhere
sudo spctl --master-disable
sudo defaults write /var/db/SystemPolicy-prefs.plist enabled -string no
defaults write com.apple.LaunchServices LSQuarantine -bool false

# Change indexing order and disable some search results in Spotlight
# defaults write com.apple.spotlight orderedItems -array \
#   '{"enabled" = 1;"name" = "APPLICATIONS";}' \
#   '{"enabled" = 1;"name" = "SYSTEM_PREFS";}' \
#   '{"enabled" = 1;"name" = "DIRECTORIES";}' \
#   '{"enabled" = 1;"name" = "PDF";}' \
#   '{"enabled" = 1;"name" = "FONTS";}' \
#   '{"enabled" = 1;"name" = "DOCUMENTS";}' \
#   '{"enabled" = 0;"name" = "MESSAGES";}' \
#   '{"enabled" = 0;"name" = "CONTACT";}' \
#   '{"enabled" = 0;"name" = "EVENT_TODO";}' \
#   '{"enabled" = 0;"name" = "IMAGES";}' \
#   '{"enabled" = 0;"name" = "BOOKMARKS";}' \
#   '{"enabled" = 0;"name" = "MUSIC";}' \
#   '{"enabled" = 0;"name" = "MOVIES";}' \
#   '{"enabled" = 0;"name" = "PRESENTATIONS";}' \
#   '{"enabled" = 0;"name" = "SPREADSHEETS";}' \
#   '{"enabled" = 0;"name" = "SOURCE";}' \
#   '{"enabled" = 0;"name" = "MENU_DEFINITION";}' \
#   '{"enabled" = 0;"name" = "MENU_OTHER";}' \
#   '{"enabled" = 0;"name" = "MENU_CONVERSION";}' \
#   '{"enabled" = 0;"name" = "MENU_EXPRESSION";}' \
#   '{"enabled" = 0;"name" = "MENU_WEBSEARCH";}' \
#   '{"enabled" = 0;"name" = "MENU_SPOTLIGHT_SUGGESTIONS";}'
# killall mds > /dev/null 2>&1
# sudo mdutil -i on / > /dev/null
# sudo mdutil -E / > /dev/null

# Finder: increase window resize speed
defaults write NSGlobalDomain NSWindowResizeTime -float 0

# Finder: disable open/close window animation
defaults write -g QLPanelAnimationDuration -float 0

# Finder: disable open info window in finder animation
defaults write com.apple.finder DisableAllAnimations -bool true

# Finder: expand save panel by default
defaults write NSGlobalDomain NSNavPanelExpandedStateForSaveMode -bool true
defaults write NSGlobalDomain NSNavPanelExpandedStateForSaveMode2 -bool true
defaults write NSGlobalDomain PMPrintingExpandedStateForPrint -bool true
defaults write NSGlobalDomain PMPrintingExpandedStateForPrint2 -bool true

# Finder: quit printer app after jobs complete
defaults write com.apple.print.PrintingPrefs "Quit When Finished" -bool true

# System: disable system wide resume
defaults write NSGlobalDomain NSQuitAlwaysKeepsWindows -bool false

# System: disable automatic termination of inactive apps
defaults write NSGlobalDomain NSDisableAutomaticTermination -bool true

# System: save to disk instead of iCloud by default
defaults write NSGlobalDomain NSDocumentSaveNewDocumentsToCloud -bool false

# System: check for software update daily
defaults write com.apple.SoftwareUpdate ScheduleFrequency -int 1

# System: remove duplicate menu in `open with`
/System/Library/Frameworks/CoreServices.framework/Frameworks/LaunchServices.framework/Support/lsregister -kill -r -domain local -domain system -domain user

# System: disable smart quotes and dashes
defaults write NSGlobalDomain NSAutomaticQuoteSubstitutionEnabled -bool false
defaults write NSGlobalDomain NSAutomaticDashSubstitutionEnabled -bool false

# System: disalbe hibernate
sudo pmset -a hibernatemode 0

# System: remove sleep image
sudo rm /Private/var/vm/sleepimage
sudo touch /Private/var/vm/sleepimage
sudo chflags uchg /Private/var/vm/sleepimage

# System: disable sudden motion sensor
sudo pmset -a sms 0

# System: reduce transparency
defaults write com.apple.universalaccess reduceTransparency -bool true

# System: set standby delay to 24 hours
sudo pmset -a standbydelay 86400

# System: enabling full keyboard access for all controls
defaults write NSGlobalDomain AppleKeyboardUIMode -int 3

# System: disabling press-and-hold
defaults write NSGlobalDomain ApplePressAndHoldEnabled -bool false

# System: setting a blazingly fast keyboard repeat rate
defaults write NSGlobalDomain KeyRepeat -int 1
defaults write NSGlobalDomain InitialKeyRepeat -int 8
defaults write NSGlobalDomain com.apple.scrollwheel.scaling -int 4

# System: disable auto-correct
defaults write NSGlobalDomain NSAutomaticSpellingCorrectionEnabled -bool false

# System: trackpad and mouse speed
defaults write -g com.apple.trackpad.scaling 4
defaults write -g com.apple.mouse.scaling 2.8

# System: disable display from automatically adjusting brightness
sudo defaults write /Library/Preferences/com.apple.iokit.AmbientLightSensor "Automatic Display Enabled" -bool false

# System: disable keyboard from automatically adjust backlight brightness
sudo defaults write /Library/Preferences/com.apple.iokit.AmbientLightSensor "Automatic Keyboard Enabled" -bool false

# System: requiring password immediately after sleep
defaults write com.apple.screensaver askForPassword -int 1
defaults write com.apple.screensaver askForPasswordDelay -int 0

# System: screenshot
mkdir $HOME/Screenshots
defaults write com.apple.screencapture location -string "${HOME}/Screenshots"
defaults write com.apple.screencapture type -string "png"
defaults write com.apple.screencapture disable-shadow -bool true
defaults write com.apple.screencapture “include-date” -int 0

# System: enable smooth font rendering in none apple lcd
defaults write NSGlobalDomain AppleFontSmoothing -int 2

# System: hide hidden files in finder
defaults write com.apple.Finder AppleShowAllFiles -bool false

# System: show filename extension in finder
defaults write NSGlobalDomain AppleShowAllExtensions -bool true

# System: disable warning when changing file extension
defaults write com.apple.finder FXEnableExtensionChangeWarning -bool false

# System: use list view in all Finder windows by default
defaults write com.apple.finder FXPreferredViewStyle -string "Nlsv"

# System: do not create .DS_Store in network volume
defaults write com.apple.desktopservices DSDontWriteNetworkStores -bool true

# System: allow text selection in quick look
defaults write com.apple.finder QLEnableTextSelection -bool true

# System: allow cmd + q to quit finder
defaults write com.apple.finder QuitMenuItem -bool true

# System: show icons for harddrive, server, or removeable media on desktop
defaults write com.apple.finder ShowExternalHardDrivesOnDesktop -bool true
defaults write com.apple.finder ShowHardDrivesOnDesktop -bool true
defaults write com.apple.finder ShowMountedServersOnDesktop -bool true
defaults write com.apple.finder ShowRemovableMediaOnDesktop -bool true

# System: hide status bar in finder
defaults write com.apple.finder ShowStatusBar -bool false

# Finder: show path bar
defaults write com.apple.finder ShowPathbar -bool true

# Finder: display posix path in title bar
defaults write com.apple.finder _FXShowPosixPathInTitle -bool true

# Finder: keep dir on top when sort by name
defaults write com.apple.finder _FXSortFoldersFirst -bool true

# Finder: when performing a search, search the current dir by default
defaults write com.apple.finder FXDefaultSearchScope -string "SCcf"

# Finder; disable warning when changing file extension
defaults write com.apple.finder FXEnableExtensionChangeWarning -bool false

# Finder: enable spring loading for dirs
defaults write NSGlobalDomain com.apple.springing.enabled -bool true

# Finder: remove spring loading animation for dirs
defaults write NSGlobalDomain com.apple.springing.delay -float 0

# Finder: show item info near icons on the desktop and in other icon views
/usr/libexec/PlistBuddy -c "Set :DesktopViewSettings:IconViewSettings:showItemInfo true" ~/Library/Preferences/com.apple.finder.plist
/usr/libexec/PlistBuddy -c "Set :FK_StandardViewSettings:IconViewSettings:showItemInfo true" ~/Library/Preferences/com.apple.finder.plist
/usr/libexec/PlistBuddy -c "Set :StandardViewSettings:IconViewSettings:showItemInfo true" ~/Library/Preferences/com.apple.finder.plist

# Finder: show item info in the right
/usr/libexec/PlistBuddy -c "Set DesktopViewSettings:IconViewSettings:labelOnBottom false" ~/Library/Preferences/com.apple.finder.plist

# Finder: enable snap-to-grid
/usr/libexec/PlistBuddy -c "Set :DesktopViewSettings:IconViewSettings:arrangeBy grid" ~/Library/Preferences/com.apple.finder.plist
/usr/libexec/PlistBuddy -c "Set :FK_StandardViewSettings:IconViewSettings:arrangeBy grid" ~/Library/Preferences/com.apple.finder.plist
/usr/libexec/PlistBuddy -c "Set :StandardViewSettings:IconViewSettings:arrangeBy grid" ~/Library/Preferences/com.apple.finder.plist

# Finder: increase grid spacing
/usr/libexec/PlistBuddy -c "Set :DesktopViewSettings:IconViewSettings:gridSpacing 48" ~/Library/Preferences/com.apple.finder.plist
/usr/libexec/PlistBuddy -c "Set :FK_StandardViewSettings:IconViewSettings:gridSpacing 48" ~/Library/Preferences/com.apple.finder.plist
/usr/libexec/PlistBuddy -c "Set :StandardViewSettings:IconViewSettings:gridSpacing 48" ~/Library/Preferences/com.apple.finder.plist

# Finder: increase icon size
/usr/libexec/PlistBuddy -c "Set :DesktopViewSettings:IconViewSettings:iconSize 60" ~/Library/Preferences/com.apple.finder.plist
/usr/libexec/PlistBuddy -c "Set :FK_StandardViewSettings:IconViewSettings:iconSize 60" ~/Library/Preferences/com.apple.finder.plist
/usr/libexec/PlistBuddy -c "Set :StandardViewSettings:IconViewSettings:iconSize 60" ~/Library/Preferences/com.apple.finder.plist

# Dock: reduce dock icon size
defaults write com.apple.dock tilesize -int 36

# Dock: speed up mission control animation
defaults write com.apple.dock expose-animation-duration -float 0
defaults write com.apple.dock "expose-group-by-app" -bool true

# System: disable the over-the-top focus ring animation
defaults write NSGlobalDomain NSUseAnimatedFocusRing -bool false

# Dock: auto hide
defaults write com.apple.dock autohide -bool true
defaults write com.apple.dock autohide-delay -float 0
defaults write com.apple.dock autohide-time-modifier -float 0
defaults write com.apple.dock launchanim -bool false

# Finder: disable warning on empty trash
defaults write com.apple.finder WarnOnEmptyTrash -bool false

# System: enable airdrop on unsupport mac
defaults write com.apple.NetworkBrowser BrowseAllInterfaces -bool true

# System: enable the MacBook Air SuperDrive on any Mac
sudo nvram boot-args="mbasd=1"

# Finder: show library dir
chflags nohidden ~/Library

# Finder: show /Volumes
sudo chflags nohidden /Volumes

# Dock: minimize/maximize effect
defaults write com.apple.dock mineffect -string "scale"

# Dock: minimize window to app icon
defaults write com.apple.dock minimize-to-application -bool false

# Dock: Enable spring loading for all Dock items
defaults write com.apple.dock enable-spring-load-actions-on-all-items -bool true

# Dock: show indicator lights for open applications
defaults write com.apple.dock show-process-indicators -bool true

# Dock: don’t animate opening applications
defaults write com.apple.dock launchanim -bool false


## Safari
# Don't send search queries to Apple
defaults write com.apple.Safari UniversalSearchEnabled -bool false
defaults write com.apple.Safari SuppressSearchSuggestions -bool true

# Hiding bookmarks bar by default
defaults write com.apple.Safari ShowFavoritesBar -bool false

# Hiding sidebar in Top Sites
defaults write com.apple.Safari ShowSidebarInTopSites -bool false

# Disabling thumbnail cache
defaults write com.apple.Safari DebugSnapshotsUpdatePolicy -int 2

# Enabling debug menu
defaults write com.apple.Safari IncludeInternalDebugMenu -bool true

# Making search banners default to Contains instead of Starts With
defaults write com.apple.Safari FindOnPageMatchesWordStartsOnly -bool false

# Enabling the Develop menu and the Web Inspector
defaults write com.apple.Safari IncludeDevelopMenu -bool true
defaults write com.apple.Safari WebKitDeveloperExtrasEnabledPreferenceKey -bool true
defaults write com.apple.Safari "com.apple.Safari.ContentPageGroupIdentifier.WebKit2DeveloperExtrasEnabled" -bool true

# Adding a context menu item for showing the Web Inspector in web views
defaults write NSGlobalDomain WebKitDeveloperExtras -bool true

# Allow backspace go to previous page
defaults write com.apple.Safari com.apple.Safari.ContentPageGroupIdentifier.WebKit2BackspaceKeyNavigationEnabled -bool true

# Disable DNS prefetch
defaults write com.apple.safari WebKitDNSPrefetchingEnabled -boolean false

## Mail
# Setting email addresses to copy
defaults write com.apple.mail AddressesIncludeNameOnPasteboard -bool false

# Disable reply animation
defaults write com.apple.mail DisableReplyAnimations -bool true
defaults write com.apple.mail DisableSendAnimations -bool true

## Terminal
# Enabling UTF-8 ONLY and setting the Basic theme by default
defaults write com.apple.terminal StringEncodings -array 4
defaults write com.apple.Terminal "Default Window Settings" -string "Basic"
defaults write com.apple.Terminal "Startup Window Settings" -string "Basic"

## Time machine
# Prevent Time Machine from prompting
defaults write com.apple.TimeMachine DoNotOfferNewDisksForBackup -bool true

# Disable local Time Machine backups
hash tmutil &> /dev/null && sudo tmutil disablelocal

## Message
# Disable smart quotes
defaults write com.apple.messageshelper.MessageController SOInputLineSettings -dict-add "automaticQuoteSubstitutionEnabled" -bool false

# Disable spell checking
defaults write com.apple.messageshelper.MessageController SOInputLineSettings -dict-add "continuousSpellCheckingEnabled" -bool false

# Enable emoji
defaults write com.apple.messageshelper.MessageController SOInputLineSettings -dict-add "automaticEmojiSubstitutionEnablediMessage" -bool true

## TextEdit
# Set plain text to default
defaults write com.apple.TextEdit RichText -int 0

## Photos
# Disable auto start of Photos.app
defaults -currentHost write com.apple.ImageCapture disableHotPlug -bool true

# Reset
find ~/Library/Application\ Support/Dock -name "*.db" -maxdepth 1 -delete
for app in "Activity Monitor" "Address Book" "Calendar" "Contacts" "cfprefsd" \
  "Dock" "Finder" "Mail" "Messages" "Safari" "SystemUIServer" \
  "Terminal" "Transmission"; do
  killall "${app}" > /dev/null 2>&1
done
