#!/usr/bin/env sh

# This script will creates symlinks from any desired dotfiles in ~/.dotfiles to home directory

files=$( sh <<EOF
ls -1
EOF
)

newdir=$HOME/.dotfiles
olddir=$HOME/.dotfiles_old

echo "\nCreating $olddir for backup of any existing dotfiles in home directory\n"
mkdir -p $olddir
echo "...done\n"

echo "Changing to the $newdir directory\n"
cd $newdir

for file in $files; do
  if [[ "$file" != "README.md" && "$file" != "setup" ]]; then
    echo "Moving .$file dotfiles from home directory to $olddir if existing";
    mv $HOME/.$file $olddir;
    echo "Creating symlink to $file in home directory.";
    ln -s $newdir/$file $HOME/.$file;
  fi
done

echo "\nCreating directories for vim\n"
mkdir -p $HOME/.vim/autoload
mkdir -p $HOME/.vim/backup
mkdir -p $HOME/.vim/bundle
mkdir -p $HOME/.vim/colors
mkdir -p $HOME/.vim/tmp
mkdir -p $HOME/.vim/undo

echo "\nCreating directories for zsh\n"
mkdir -p $HOME/.zsh

echo "\nCloning zsh plugin"
cd $HOME/.zsh && git clone https://github.com/zsh-users/zsh-completions.git
cd $HOME/.zsh && git clone https://github.com/zsh-users/zsh-syntax-highlighting.git
cd $HOME/.zsh && git clone https://github.com/zsh-users/zsh-history-substring-search.git

echo "\nCreating directories for tmux\n"
mkdir -p $HOME/.tmux/plugins

echo "\nCloning zsh plugin"
cd $HOME/.tmux/plugins && git clone https://github.com/tmux-plugins/tpm.git
cd $HOME/.tmux/plugins && git clone https://github.com/tmux-plugins/tmux-open.git
cd $HOME/.tmux/plugins && git clone https://github.com/tmux-plugins/tmux-yank.git
cd $HOME/.tmux/plugins && git clone https://github.com/tmux-plugins/tmux-copycat.git
cd $HOME/.tmux/plugins && git clone https://github.com/tmux-plugins/tmux-sessionist.git
cd $HOME/.tmux/plugins && git clone https://github.com/tmux-plugins/tmux-prefix-highlight.git

echo "\nDone!!\n"
