#!/usr/bin/env python3

import json
import sys

READ_ERR_MSG = 'Cannot read input json. It may be in malformed format.'
NO_INPUT_MSG = 'No json input.'


def has_stdin():
    return not sys.stdin.isatty()


def has_arg():
    return len(sys.argv) > 1


def read_stdin():
    try:
        return json.loads(sys.stdin.read())
    except Exception:
        print(READ_ERR_MSG)
        sys.exit(1)


def read_arg():
    try:
        return json.loads(sys.argv[1])
    except Exception:
        print(READ_ERR_MSG)
        sys.exit(1)


def print_json(j):
    print(json.dumps(j, indent=4, sort_keys=True))


def main():
    if has_stdin():
        j = read_stdin()
        print_json(j)
    elif has_arg():
        j = read_arg()
        print_json(j)
    else:
        print(NO_INPUT_MSG)


if __name__ == '__main__':
    main()

